all:
  hosts:
    web:
      ansible_host: "{{ lookup('env', 'EC2_IP') }}"
      ansible_user: ec2-user
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'